### ISSUE TITLE
Error in implementing websocket

### ISSUE THREAD

**Issue by Studyleague** [upstox/upstox-php#5]
Just wanted to quickly understand a few things,
1. We've tried integrating the [PHP sdk of web socket](https://github.com/upstox/upstox-php/tree/master/examples/websocket/market_data) to get the market data but encountered few issues,
1. As per the github repo, it was required to install the "protobuf" package via composer but there is no such package so we installed "google/protobuf" pkg which was available & shown as an alternative. PFA screenshot of the same.
2. Similarly, "websocket-client" was also not there so we installed "gos/websocket-client" pkg which was available & shown as an alternative. PFA screenshot of the same. Kindly confirm if these packages are ok to work with or any other pkg has to be installed and also let us know if any changes are required to be made in the [websocket_client.php](https://github.com/upstox/upstox-php/blob/master/examples/websocket/market_data/websocket_client.php) code as we installed different type of pkg.
3. After going through all the steps as per the SDK documentation, changing the `ACCESS_TOKEN`, we tried running the  websocket_client.php file but encountered the error shown in the attachment named "error". Pls guide us what could be the reason.
4. Also, pls let know if the file runs successfully then, what's the next step to get the LTP values of all 2500 stocks that we want , in real-time.

![protobuf install](https://github.com/upstox/upstox-php/assets/42137207/82bfe714-92a9-4598-a82a-25c877b3fa81)

![websocket-client  installation](https://github.com/upstox/upstox-php/assets/42137207/ac806b39-6312-4539-8242-1a7be704e781)
![error](https://github.com/upstox/upstox-php/assets/42137207/e94f9e23-d618-47b3-8a38-0202bda1f32e)

**Comment by Studyleague** [comment]
Issue Title: Error occurred during parsing: Fail to push limit

Description: I encountered the error message "Error occurred during parsing: Fail to push limit" while attempting to deserialize protobuf data in the Upstox WebSocket implementation. This issue arises when parsing the data using Google Protocol Buffers (protobuf) with PHP (Laravel) on a Windows system. I have attached relevant screenshots to assist in diagnosing the issue. Any guidance or insights into resolving this error would be greatly appreciated.

![websocket issue](https://github.com/upstox/upstox-php/assets/42137207/8c5a53af-8ed9-444f-99e2-7b4f9635ec64)

**Comment by janakkapadia** [comment]
> Just wanted to quickly understand a few things,
> 
> 1. We've tried integrating the [PHP sdk of web socket](https://github.com/upstox/upstox-php/tree/master/examples/websocket/market_data) to get the market data but encountered few issues,
> 2. As per the github repo, it was required to install the "protobuf" package via composer but there is no such package so we installed "google/protobuf" pkg which was available & shown as an alternative. PFA screenshot of the same.
> 3. Similarly, "websocket-client" was also not there so we installed "gos/websocket-client" pkg which was available & shown as an alternative. PFA screenshot of the same. Kindly confirm if these packages are ok to work with or any other pkg has to be installed and also let us know if any changes are required to be made in the [websocket_client.php](https://github.com/upstox/upstox-php/blob/master/examples/websocket/market_data/websocket_client.php) code as we installed different type of pkg.
> 4. After going through all the steps as per the SDK documentation, changing the `ACCESS_TOKEN`, we tried running the  websocket_client.php file but encountered the error shown in the attachment named "error". Pls guide us what could be the reason.
> 5. Also, pls let know if the file runs successfully then, what's the next step to get the LTP values of all 2500 stocks that we want , in real-time.
> 
> ![protobuf install](https://private-user-images.githubusercontent.com/42137207/270931037-82bfe714-92a9-4598-a82a-25c877b3fa81.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODAyNDksIm5iZiI6MTcwMjk3OTk0OSwicGF0aCI6Ii80MjEzNzIwNy8yNzA5MzEwMzctODJiZmU3MTQtOTJhOS00NTk4LWE4MmEtMjVjODc3YjNmYTgxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQwOTU5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWUyYzA3NDVlYWNkOTA0YTdiNWM5ZDhiZmJmZTE4YjNmMzgyZTZkZTA4NGMzYzc4ZjU3ZjMzYzdjNTJiZjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QzwjlRR1rdW4BXIKpNWXjVJYxKww-RYnCCMkYGDIsWc)
> 
> ![websocket-client installation](https://private-user-images.githubusercontent.com/42137207/270931056-ac806b39-6312-4539-8242-1a7be704e781.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODAyNDksIm5iZiI6MTcwMjk3OTk0OSwicGF0aCI6Ii80MjEzNzIwNy8yNzA5MzEwNTYtYWM4MDZiMzktNjMxMi00NTM5LTgyNDItMWE3YmU3MDRlNzgxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQwOTU5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTE0ZGM5YWI3ZjhlMDJhMzExMmRlZDk5ZjA0ODZjZTkxYWQ2YjE5NjAwY2FlOTM0YTY4NzgyN2UxMzZjOTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K4eMShMxIEKdk0P6UMPY4s-JBsXWdwwZjooelaSPHQ8) ![error](https://private-user-images.githubusercontent.com/42137207/270931065-e94f9e23-d618-47b3-8a38-0202bda1f32e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODAyNDksIm5iZiI6MTcwMjk3OTk0OSwicGF0aCI6Ii80MjEzNzIwNy8yNzA5MzEwNjUtZTk0ZjllMjMtZDYxOC00N2IzLThhMzgtMDIwMmJkYTFmMzJlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQwOTU5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmJjZDMwZmJkMWY3MGUzNDJjOTI0OGQyNDAxZDNjNDE4OTIxYTgyOWJkYjkzYTQ0ZGQxYmU5ZDA4MjI5MjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BCCZqf3p1HqZDk86Dhp-unS1WMBxngjYYEAkQ62WFuM)

Same Issue for me

**Comment by Rahulzz** [comment]
@Studyleague  @janakkapadia 

Thank you for letting us know about the issues with the sample WebSocket code on GitHub. We appreciate your feedback, as it helps us improve our resources.

We have addressed the problem by updating the code. The new version uses different libraries that are currently available and should resolve the dependency issues you experienced. Please try out the updated code and see if it works for your needs.

If you encounter any further issues or have additional feedback, don't hesitate to drop a note on our community forum at [Upstox Developer API Community](https://community.upstox.com/c/developer-api/15). This forum is actively monitored, and our team, as well as the community members, will be more than happy to assist you.

Your contributions and feedback are immensely valuable to us, and we're committed to ensuring a smooth experience with our tools and resources.

Thanks!!
