### ISSUE TITLE
Error  Class "Com\Upstox\Marketdatafeeder\Rpc\Proto\FeedResponse" not found.

### ISSUE THREAD

**Issue by janakkapadia** [upstox/upstox-php#9]
FeedResponse class not fount showing error so how can i decode response

**Comment by KetanGupta12** [comment]
@janakkapadia 

Are you still experiencing this issue?

If yes, please raise a query on the [Upstox community](https://community.upstox.com/c/developer-api). This is where both our team and the active developer community are diligently checking and responding.

Thanks!
